/**
 * plugins/withXcode26Compat.js
 * Lexi-Lens — iOS build automation (May 30, 2026)
 *
 * iOS-only Expo config plugin that re-applies the Xcode 26 + React Native 0.81
 * + Expo SDK 54 archive-compatibility fixes on every `npx expo prebuild`.
 *
 * ─── Why this exists ─────────────────────────────────────────────────────
 *
 * `ios/` is gitignored and fully regenerated by `prebuild --clean`. Four
 * manual edits were required after every regeneration to produce a
 * TestFlight-archivable project (documented in
 * docs/iOS_LOCAL_TESTFLIGHT_RUNBOOK.md after the 9-hour session that produced
 * build 1.0.31). Hand-applying four edits every prebuild is fragile and
 * forgettable — exactly the recurring-trap class the Android build playbook
 * exists to kill. This plugin makes three of the four survive prebuild
 * automatically. (The fourth — opening the .xcworkspace not the .xcodeproj —
 * is a user action in Xcode, not a file edit, so it stays in the runbook.)
 *
 * Mirrors the proven pattern of plugins/withReleaseSigningConfig.js
 * (Android) and plugins/withGradleMemory.js (Android Gradle memory).
 *
 * ─── What it automates ───────────────────────────────────────────────────
 *
 * Four modifiers:
 *   Fix #1  Podfile post_install (SWIFT_ENABLE_EXPLICIT_MODULES=NO, fmt c++17)
 *   Fix #2  ENABLE_USER_SCRIPT_SANDBOXING=NO on the app project
 *   Fix #3  ios/.xcode.env.local — absolute NODE_BINARY (Sharp Edge #5) +
 *           SENTRY_DISABLE_AUTO_UPLOAD
 *   Fix #4  "Copy Hermes dSYM into archive" build phase (formerly TODO 2 —
 *           kills the "Upload Symbols Failed" warning at Distribute)
 *
 * The only iOS-archive step that stays manual is opening the .xcworkspace
 * (not the .xcodeproj) in Xcode — a user action, not a file edit.
 *
 *   Fix #1  (Podfile post_install → Pods/Pods.xcodeproj):
 *     - SWIFT_ENABLE_EXPLICIT_MODULES = NO on ALL Pod targets. Xcode 26
 *       defaults this YES, which breaks CocoaPods module-map generation
 *       (~25 "modulemap not found" errors, archive dies in ~3s). RN 0.81.1
 *       auto-fixes this ONLY for precompiled-XCFramework projects; we use
 *       buildReactNativeFromSource:true, which bypasses that auto-fix.
 *     - CLANG_CXX_LANGUAGE_STANDARD = c++17 on fmt + RCT-Folly. Xcode 26
 *       defaults to c++20, under which fmt's consteval format-string
 *       validation fails (facebook/react-native#55601).
 *
 *   Fix #2  (app target's *.xcodeproj/project.pbxproj):
 *     - ENABLE_USER_SCRIPT_SANDBOXING = NO. Xcode 26 defaults YES, which
 *       blocks the "Bundle React Native code and images" build phase from
 *       writing its output (ip.txt). Note: this is the APP project, NOT the
 *       Pods project — a frequent confusion. Applied structurally via
 *       withXcodeProject so it covers every build configuration regardless
 *       of the baked variant name (LexiLensStaging / LexiLensDev / LexiLens).
 *
 *   Fix #3  (ios/.xcode.env.local) — TWO env keys:
 *
 *     (a) NODE_BINARY=<absolute path to node>  [Sharp Edge #5, added 2026-05-30]
 *         React Native's scripts/xcode/with-environment.sh initialises
 *         NODE_BINARY from `command -v node`. When Xcode is launched from
 *         Finder/Dock (not a terminal with nvm active), that resolves to
 *         EMPTY — and the auto-generated ios/.xcode.env uses the same empty
 *         `$(command -v node)`. with-environment.sh then falls back to
 *         scripts/find-node-for-xcode.sh, which puts `node` on PATH (the
 *         "Now using node vXX" line) but NEVER sets NODE_BINARY. The Hermes
 *         "[Hermes] Replace Hermes for the right configuration" build phase
 *         then runs `"$NODE_BINARY" .../replace_hermes_version.js` with
 *         NODE_BINARY="" → bash executes an empty command word →
 *         `PhaseScriptExecution failed ... line 9: : command not found`.
 *         The archive dies before compiling a single file.
 *
 *         Fix: pin NODE_BINARY to an ABSOLUTE path in .xcode.env.local, which
 *         with-environment.sh sources AFTER .xcode.env, so it wins and the
 *         fragile nvm fallback is never entered. We resolve the path from
 *         `process.execPath` — the node binary currently running prebuild,
 *         which on the Mac IS the developer's active nvm/Homebrew node. It is
 *         REWRITTEN on every prebuild, so it self-heals across node upgrades
 *         (no stale version path can linger). Assumption: the node you run
 *         `expo prebuild` with is the node Xcode should use for the archive —
 *         true for a single-machine solo build; revisit only if prebuild and
 *         archive ever run under different node managers.
 *
 *     (b) SENTRY_DISABLE_AUTO_UPLOAD=true. Without a SENTRY_AUTH_TOKEN the
 *         Sentry "Upload Debug Symbols" build phase fails the archive. CLI env
 *         vars passed to `expo run:ios` do NOT propagate to Xcode Archive
 *         (different process tree), so this must live in the env file.
 *         TODO (separate item): when SENTRY_AUTH_TOKEN is configured for real
 *         symbolication, drop this and let symbols upload.
 *
 * ─── Android safety ──────────────────────────────────────────────────────
 *
 * Every modifier here is iOS-scoped: withPodfile, withXcodeProject, and a
 * withDangerousMod gated on platform 'ios'. None fire during
 * `npx expo prebuild --platform android`. The generated android/ folder is
 * byte-identical with or without this plugin. (Verification recipe: the same
 * fc/diff approach used in docs/BUILD_ANDROID_LOCAL.md §6, with platforms
 * swapped.)
 *
 * ─── Idempotency ─────────────────────────────────────────────────────────
 *
 * All three edits detect whether they've already been applied and skip if so,
 * so running prebuild repeatedly is safe and never duplicates lines.
 */

const fs = require('fs');
const path = require('path');
const {
  withPodfile,
  withXcodeProject,
  withDangerousMod,
} = require('@expo/config-plugins');

// ── Fix #1 — Podfile post_install block (Pods targets) ──────────────────────
//
// We inject our per-target loop INSIDE the existing `post_install do |installer|`
// block, immediately after Expo's react_native_post_install(...) call, rather
// than appending a second post_install (CocoaPods only honors one). The marker
// comment makes the edit idempotent.

const PODFILE_MARKER = '# withXcode26Compat: Xcode 26 + RN 0.81 archive fixes';

const PODFILE_INJECTION = `
    ${PODFILE_MARKER}
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |bc|
        # Disable Swift explicit modules on all Pod targets (Xcode 26 default
        # YES breaks CocoaPods module maps). See iOS runbook Sharp Edge #2.
        bc.build_settings['SWIFT_ENABLE_EXPLICIT_MODULES'] = 'NO'
        # Force c++17 on fmt + RCT-Folly (c++20 breaks fmt consteval under
        # Xcode 26). See iOS runbook Sharp Edge #1 / facebook/react-native#55601.
        if ['fmt', 'RCT-Folly'].include?(target.name)
          bc.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
        end
      end
    end`;

const withXcode26Podfile = (config) =>
  withPodfile(config, (config) => {
    let contents = config.modResults.contents;

    if (contents.includes(PODFILE_MARKER)) {
      return config; // already applied — idempotent
    }

    // Anchor on Expo's react_native_post_install(...) call, which lives inside
    // the post_install block. Insert our loop right after that call's closing
    // ")" so we are guaranteed to be inside the post_install scope.
    const anchor = /react_native_post_install\([\s\S]*?\)\n/;
    const match = contents.match(anchor);

    if (match) {
      const insertAt = match.index + match[0].length;
      contents =
        contents.slice(0, insertAt) + PODFILE_INJECTION + '\n' + contents.slice(insertAt);
      console.log('[withXcode26Compat] Injected Podfile post_install fixes (Fix #1).');
    } else {
      // Fallback: if the anchor moved (Expo template change), don't throw —
      // log loudly. A missing Fix #1 fails the archive with a clear modulemap
      // error, which is debuggable. Throwing would break prebuild entirely.
      console.error(
        '[withXcode26Compat] WARNING: could not locate react_native_post_install ' +
          'anchor in Podfile. Fix #1 (SWIFT_ENABLE_EXPLICIT_MODULES / fmt c++17) ' +
          'was NOT applied — archive will fail with modulemap errors until the ' +
          'Podfile post_install block is patched manually (see iOS runbook Fix #1).',
      );
    }

    config.modResults.contents = contents;
    return config;
  });

// ── Fix #2 — ENABLE_USER_SCRIPT_SANDBOXING = NO (app .xcodeproj) ─────────────
//
// Structural edit via withXcodeProject: set the build setting on every build
// configuration in the app project. This is variant-agnostic (works whether
// the baked target is LexiLensStaging, LexiLensDev, or LexiLens) and more
// robust than a sed against a hard-coded project name.

const withXcode26Sandboxing = (config) =>
  withXcodeProject(config, (config) => {
    const project = config.modResults;
    const configurations = project.pbxXCBuildConfigurationSection();

    let patched = 0;
    for (const key of Object.keys(configurations)) {
      const entry = configurations[key];
      // Skip comment entries (xcode lib intersperses "<key>_comment" strings).
      if (!entry || typeof entry !== 'object' || !entry.buildSettings) continue;
      entry.buildSettings.ENABLE_USER_SCRIPT_SANDBOXING = 'NO';
      patched += 1;
    }

    console.log(
      `[withXcode26Compat] Set ENABLE_USER_SCRIPT_SANDBOXING=NO on ${patched} ` +
        'app build configurations (Fix #2).',
    );
    return config;
  });

// ── Fix #3 — ios/.xcode.env.local (NODE_BINARY + SENTRY_DISABLE_AUTO_UPLOAD) ──
//
// withDangerousMod is the right primitive for a raw file the Xcode templates
// don't model. Gated on 'ios' — never fires for `expo prebuild --platform
// android`. The two keys use deliberately different write strategies:
//
//   • NODE_BINARY        → SELF-HEALING: any prior NODE_BINARY line is stripped
//                          and rewritten to the current `process.execPath` on
//                          every prebuild, so a stale node-version path can
//                          never survive a node upgrade. (Sharp Edge #5.)
//   • SENTRY_DISABLE_...  → IDEMPOTENT APPEND: added only if absent, never
//                          churned, so a manually-added SENTRY_AUTH_TOKEN or
//                          other lines in the file are preserved untouched.

const SENTRY_LINE = 'export SENTRY_DISABLE_AUTO_UPLOAD=true';

const withXcode26EnvLocal = (config) =>
  withDangerousMod(config, [
    'ios',
    (config) => {
      const file = path.join(
        config.modRequest.platformProjectRoot,
        '.xcode.env.local',
      );

      let existing = '';
      try {
        existing = fs.readFileSync(file, 'utf8');
      } catch {
        existing = ''; // file may not exist yet — we'll create it
      }

      // ── (a) NODE_BINARY — resolve absolute path of the node running prebuild.
      // process.execPath is always an absolute path to the active node binary.
      // Light guard: if it somehow doesn't look like a real path, skip rather
      // than write a broken line (never break prebuild over this).
      const nodePath = process.execPath;
      const nodeOk =
        typeof nodePath === 'string' &&
        nodePath.startsWith('/') &&
        fs.existsSync(nodePath);

      // Strip ANY pre-existing NODE_BINARY line (self-heal across upgrades).
      let lines = existing
        .split('\n')
        .filter((l) => !/^\s*export\s+NODE_BINARY=/.test(l));

      if (nodeOk) {
        lines.push(`export NODE_BINARY="${nodePath}"`);
        console.log(
          `[withXcode26Compat] Set NODE_BINARY="${nodePath}" in ` +
            'ios/.xcode.env.local (Fix #3a — Sharp Edge #5). This prevents the ' +
            'Hermes "Replace Hermes" phase from failing with ' +
            '"line 9: : command not found" when Xcode is launched without ' +
            'node on PATH.',
        );
      } else {
        console.error(
          '[withXcode26Compat] WARNING: could not resolve a valid absolute node ' +
            `path from process.execPath ("${nodePath}"). NODE_BINARY was NOT ` +
            'written. If the archive fails in the Hermes script with ' +
            '"line 9: : command not found", set NODE_BINARY manually in ' +
            'ios/.xcode.env.local (see iOS runbook Sharp Edge #5).',
        );
      }

      // ── (b) SENTRY_DISABLE_AUTO_UPLOAD — idempotent append.
      if (!lines.some((l) => l.includes('SENTRY_DISABLE_AUTO_UPLOAD'))) {
        lines.push(SENTRY_LINE);
        console.log(
          '[withXcode26Compat] Appended SENTRY_DISABLE_AUTO_UPLOAD=true to ' +
            'ios/.xcode.env.local (Fix #3b).',
        );
      }

      // Normalise: drop all blank lines (file is export statements only),
      // exactly one trailing newline.
      const next = lines.filter((l) => l.trim() !== '').join('\n') + '\n';
      fs.writeFileSync(file, next);
      return config;
    },
  ]);

// ── Fix #4 — Copy Hermes dSYM into the archive (formerly runbook TODO 2) ────
//
// Symptom this kills: Xcode Organizer → Distribute → Upload finishes with
// "Upload Symbols Failed: The archive did not include a dSYM for the
// hermes.framework with the UUIDs [...]". Non-fatal (the binary still ships),
// but Hermes-engine-internal crash frames won't symbolicate on App Store
// Connect (and the same dSYM is what Sentry needs once SENTRY_AUTH_TOKEN is
// wired — see runbook TODO 3).
//
// Cause: this project uses the PREBUILT Hermes release tarball, which on RN
// 0.81 ships iOS as an XCFramework. Its dSYM lives INSIDE the xcframework
// (e.g. .../hermes.xcframework/ios-arm64/dSYMs/hermes.framework.dSYM) and is
// NOT copied into the archive's DWARF dSYM folder automatically. We add a
// run-script build phase to the app target that copies it there during the
// archive, after the framework is in place.
//
// Robustness:
//   • Locates the dSYM with `find` rather than a hardcoded path (the exact
//     layout differs between prebuilt-xcframework and from-source Hermes, and
//     across RN versions). Verified: the runbook's old hardcoded
//     `universal/hermes.framework.dSYM` path does NOT exist for RN 0.81
//     prebuilt — it's inside the xcframework slice.
//   • Excludes the simulator slice — its UUID won't match a device archive,
//     so copying it would leave the warning in place.
//   • Guards on DWARF_DSYM_FOLDER_PATH so it no-ops on normal (non-archive)
//     builds and never fails them.
//   • Idempotent: skips if a phase with our marker name already exists.

const HERMES_DSYM_PHASE_NAME = 'Copy Hermes dSYM into archive (withXcode26Compat)';

const HERMES_DSYM_SCRIPT = [
  'set -e',
  '# Apple symbol upload wants a dSYM for the prebuilt Hermes xcframework.',
  '# Only relevant during archive (DWARF_DSYM_FOLDER_PATH is set then).',
  'if [ -z "${DWARF_DSYM_FOLDER_PATH}" ]; then',
  '  echo "[hermes-dsym] Not an archive build — skipping."',
  '  exit 0',
  'fi',
  '# Find the device-slice Hermes dSYM (exclude simulator: its UUID will not',
  '# match the archived arm64 binary).',
  'HERMES_DSYM=$(find "${PODS_ROOT}/hermes-engine" -type d -name "hermes.framework.dSYM" 2>/dev/null | grep -vi "simulator\\|maccatalyst\\|tvos\\|visionos\\|xros\\|watchos\\|macosx" | head -1)',
  'if [ -z "${HERMES_DSYM}" ] || [ ! -d "${HERMES_DSYM}" ]; then',
  '  echo "[hermes-dsym] hermes.framework.dSYM not found under ${PODS_ROOT}/hermes-engine — skipping (Apple symbol upload may warn)."',
  '  exit 0',
  'fi',
  'echo "[hermes-dsym] Copying ${HERMES_DSYM} -> ${DWARF_DSYM_FOLDER_PATH}/"',
  'cp -R "${HERMES_DSYM}" "${DWARF_DSYM_FOLDER_PATH}/"',
  'echo "[hermes-dsym] Done."',
].join('\n');

const withHermesDsymCopyPhase = (config) =>
  withXcodeProject(config, (config) => {
    const project = config.modResults;

    // Idempotency: bail if our phase is already present.
    const existingPhases =
      (project.hash &&
        project.hash.project &&
        project.hash.project.objects &&
        project.hash.project.objects.PBXShellScriptBuildPhase) ||
      {};
    for (const key of Object.keys(existingPhases)) {
      const phase = existingPhases[key];
      if (
        phase &&
        typeof phase === 'object' &&
        typeof phase.name === 'string' &&
        phase.name.includes('Copy Hermes dSYM')
      ) {
        console.log(
          '[withXcode26Compat] Hermes dSYM copy phase already present — skipping (Fix #4).',
        );
        return config;
      }
    }

    // Target the application target specifically (not a test/extension target).
    const nativeTargets = project.pbxNativeTargetSection();
    let appTargetUuid;
    for (const key of Object.keys(nativeTargets)) {
      const t = nativeTargets[key];
      if (
        t &&
        typeof t === 'object' &&
        typeof t.productType === 'string' &&
        t.productType.includes('com.apple.product-type.application')
      ) {
        appTargetUuid = key;
        break;
      }
    }

    if (!appTargetUuid) {
      console.error(
        '[withXcode26Compat] WARNING: could not find an application target to ' +
          'attach the Hermes dSYM copy phase. Fix #4 NOT applied — the archive ' +
          'will still upload, but Apple will warn "Upload Symbols Failed" for ' +
          'hermes.framework. See iOS runbook Sharp Edge #3 / TODO 2.',
      );
      return config;
    }

    project.addBuildPhase(
      [],
      'PBXShellScriptBuildPhase',
      HERMES_DSYM_PHASE_NAME,
      appTargetUuid,
      { shellPath: '/bin/sh', shellScript: HERMES_DSYM_SCRIPT },
    );

    console.log(
      '[withXcode26Compat] Added "Copy Hermes dSYM into archive" build phase ' +
        'to the app target (Fix #4 — formerly TODO 2).',
    );
    return config;
  });

// ── Compose ──────────────────────────────────────────────────────────────────

const withXcode26Compat = (config) => {
  config = withXcode26Podfile(config);
  config = withXcode26Sandboxing(config);
  config = withXcode26EnvLocal(config);
  config = withHermesDsymCopyPhase(config);
  return config;
};

module.exports = withXcode26Compat;
