/**
 * plugins/withXcode26Compat.js
 * Lexi-Lens — iOS build automation (May 30, 2026)
 *
 * iOS-only Expo config plugin that re-applies the Xcode 26 + React Native 0.81
 * + Expo SDK 54 archive-compatibility fixes on every `npx expo prebuild`.
 *
 * ─── Why this exists ─────────────────────────────────────────────────────
 *
 * `ios/` is gitignored and fully regenerated by `prebuild --clean`. Four
 * manual edits were required after every regeneration to produce a
 * TestFlight-archivable project (documented in
 * docs/iOS_LOCAL_TESTFLIGHT_RUNBOOK.md after the 9-hour session that produced
 * build 1.0.31). Hand-applying four edits every prebuild is fragile and
 * forgettable — exactly the recurring-trap class the Android build playbook
 * exists to kill. This plugin makes three of the four survive prebuild
 * automatically. (The fourth — opening the .xcworkspace not the .xcodeproj —
 * is a user action in Xcode, not a file edit, so it stays in the runbook.)
 *
 * Mirrors the proven pattern of plugins/withReleaseSigningConfig.js
 * (Android) and plugins/withGradleMemory.js (Android Gradle memory).
 *
 * ─── What it automates (the 4 Xcode 26 sharp edges) ──────────────────────
 *
 *   Fix #1  (Podfile post_install → Pods/Pods.xcodeproj):
 *     - SWIFT_ENABLE_EXPLICIT_MODULES = NO on ALL Pod targets. Xcode 26
 *       defaults this YES, which breaks CocoaPods module-map generation
 *       (~25 "modulemap not found" errors, archive dies in ~3s). RN 0.81.1
 *       auto-fixes this ONLY for precompiled-XCFramework projects; we use
 *       buildReactNativeFromSource:true, which bypasses that auto-fix.
 *     - CLANG_CXX_LANGUAGE_STANDARD = c++17 on fmt + RCT-Folly. Xcode 26
 *       defaults to c++20, under which fmt's consteval format-string
 *       validation fails (facebook/react-native#55601).
 *
 *   Fix #2  (app target's *.xcodeproj/project.pbxproj):
 *     - ENABLE_USER_SCRIPT_SANDBOXING = NO. Xcode 26 defaults YES, which
 *       blocks the "Bundle React Native code and images" build phase from
 *       writing its output (ip.txt). Note: this is the APP project, NOT the
 *       Pods project — a frequent confusion. Applied structurally via
 *       withXcodeProject so it covers every build configuration regardless
 *       of the baked variant name (LexiLensStaging / LexiLensDev / LexiLens).
 *
 *   Fix #3  (ios/.xcode.env.local):
 *     - SENTRY_DISABLE_AUTO_UPLOAD=true. Without a SENTRY_AUTH_TOKEN the
 *       Sentry "Upload Debug Symbols" build phase fails the archive. CLI env
 *       vars passed to `expo run:ios` do NOT propagate to Xcode Archive
 *       (different process tree), so this must live in the env file.
 *       TODO (separate item): when SENTRY_AUTH_TOKEN is configured for real
 *       symbolication, drop this and let symbols upload.
 *
 * ─── Android safety ──────────────────────────────────────────────────────
 *
 * Every modifier here is iOS-scoped: withPodfile, withXcodeProject, and a
 * withDangerousMod gated on platform 'ios'. None fire during
 * `npx expo prebuild --platform android`. The generated android/ folder is
 * byte-identical with or without this plugin. (Verification recipe: the same
 * fc/diff approach used in docs/BUILD_ANDROID_LOCAL.md §6, with platforms
 * swapped.)
 *
 * ─── Idempotency ─────────────────────────────────────────────────────────
 *
 * All three edits detect whether they've already been applied and skip if so,
 * so running prebuild repeatedly is safe and never duplicates lines.
 */

const fs = require('fs');
const path = require('path');
const {
  withPodfile,
  withXcodeProject,
  withDangerousMod,
} = require('@expo/config-plugins');

// ── Fix #1 — Podfile post_install block (Pods targets) ──────────────────────
//
// We inject our per-target loop INSIDE the existing `post_install do |installer|`
// block, immediately after Expo's react_native_post_install(...) call, rather
// than appending a second post_install (CocoaPods only honors one). The marker
// comment makes the edit idempotent.

const PODFILE_MARKER = '# withXcode26Compat: Xcode 26 + RN 0.81 archive fixes';

const PODFILE_INJECTION = `
    ${PODFILE_MARKER}
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |bc|
        # Disable Swift explicit modules on all Pod targets (Xcode 26 default
        # YES breaks CocoaPods module maps). See iOS runbook Sharp Edge #2.
        bc.build_settings['SWIFT_ENABLE_EXPLICIT_MODULES'] = 'NO'
        # Force c++17 on fmt + RCT-Folly (c++20 breaks fmt consteval under
        # Xcode 26). See iOS runbook Sharp Edge #1 / facebook/react-native#55601.
        if ['fmt', 'RCT-Folly'].include?(target.name)
          bc.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
        end
      end
    end`;

const withXcode26Podfile = (config) =>
  withPodfile(config, (config) => {
    let contents = config.modResults.contents;

    if (contents.includes(PODFILE_MARKER)) {
      return config; // already applied — idempotent
    }

    // Anchor on Expo's react_native_post_install(...) call, which lives inside
    // the post_install block. Insert our loop right after that call's closing
    // ")" so we are guaranteed to be inside the post_install scope.
    const anchor = /react_native_post_install\([\s\S]*?\)\n/;
    const match = contents.match(anchor);

    if (match) {
      const insertAt = match.index + match[0].length;
      contents =
        contents.slice(0, insertAt) + PODFILE_INJECTION + '\n' + contents.slice(insertAt);
      console.log('[withXcode26Compat] Injected Podfile post_install fixes (Fix #1).');
    } else {
      // Fallback: if the anchor moved (Expo template change), don't throw —
      // log loudly. A missing Fix #1 fails the archive with a clear modulemap
      // error, which is debuggable. Throwing would break prebuild entirely.
      console.error(
        '[withXcode26Compat] WARNING: could not locate react_native_post_install ' +
          'anchor in Podfile. Fix #1 (SWIFT_ENABLE_EXPLICIT_MODULES / fmt c++17) ' +
          'was NOT applied — archive will fail with modulemap errors until the ' +
          'Podfile post_install block is patched manually (see iOS runbook Fix #1).',
      );
    }

    config.modResults.contents = contents;
    return config;
  });

// ── Fix #2 — ENABLE_USER_SCRIPT_SANDBOXING = NO (app .xcodeproj) ─────────────
//
// Structural edit via withXcodeProject: set the build setting on every build
// configuration in the app project. This is variant-agnostic (works whether
// the baked target is LexiLensStaging, LexiLensDev, or LexiLens) and more
// robust than a sed against a hard-coded project name.

const withXcode26Sandboxing = (config) =>
  withXcodeProject(config, (config) => {
    const project = config.modResults;
    const configurations = project.pbxXCBuildConfigurationSection();

    let patched = 0;
    for (const key of Object.keys(configurations)) {
      const entry = configurations[key];
      // Skip comment entries (xcode lib intersperses "<key>_comment" strings).
      if (!entry || typeof entry !== 'object' || !entry.buildSettings) continue;
      entry.buildSettings.ENABLE_USER_SCRIPT_SANDBOXING = 'NO';
      patched += 1;
    }

    console.log(
      `[withXcode26Compat] Set ENABLE_USER_SCRIPT_SANDBOXING=NO on ${patched} ` +
        'app build configurations (Fix #2).',
    );
    return config;
  });

// ── Fix #3 — SENTRY_DISABLE_AUTO_UPLOAD in ios/.xcode.env.local ──────────────
//
// withDangerousMod is the right primitive for a raw file the Xcode templates
// don't model. Gated on 'ios'. Idempotent: appends only if the line is absent.

const ENV_LINE = 'export SENTRY_DISABLE_AUTO_UPLOAD=true';

const withXcode26SentryEnv = (config) =>
  withDangerousMod(config, [
    'ios',
    (config) => {
      const file = path.join(
        config.modRequest.platformProjectRoot,
        '.xcode.env.local',
      );

      let existing = '';
      try {
        existing = fs.readFileSync(file, 'utf8');
      } catch {
        existing = ''; // file may not exist yet — we'll create it
      }

      if (existing.includes('SENTRY_DISABLE_AUTO_UPLOAD')) {
        return config; // already present — idempotent
      }

      const next =
        existing && !existing.endsWith('\n')
          ? existing + '\n' + ENV_LINE + '\n'
          : existing + ENV_LINE + '\n';

      fs.writeFileSync(file, next);
      console.log(
        '[withXcode26Compat] Appended SENTRY_DISABLE_AUTO_UPLOAD=true to ' +
          'ios/.xcode.env.local (Fix #3).',
      );
      return config;
    },
  ]);

// ── Compose ──────────────────────────────────────────────────────────────────

const withXcode26Compat = (config) => {
  config = withXcode26Podfile(config);
  config = withXcode26Sandboxing(config);
  config = withXcode26SentryEnv(config);
  return config;
};

module.exports = withXcode26Compat;
