/**
 * lib/phonetics.ts
 *
 * Curated pronunciation map for the common property words used in quests
 * (colours, shapes, sizes, textures, materials, plus hard-mode escalations).
 *
 * COVERAGE NOTE — read this.
 *   Property words are generated by the `generate-quest` Edge Function, so the
 *   vocabulary is OPEN-ENDED. This map covers the high-frequency words; rare or
 *   novel AI-generated words won't be here and getPhonetic() returns null. The
 *   UI hides the phonetic line in that case (and TTS still pronounces the word,
 *   so nothing is left without an audio aid). For full coverage, have the quest
 *   generator emit IPA alongside each word and store it on the property — then
 *   this map becomes a fast offline fallback rather than the primary source.
 *
 * FORMAT — General-American IPA in slashes. If you'd rather show a kid-friendly
 *   respelling (e.g. "sawft" instead of /sɔft/) for the 5–12 audience, swap the
 *   values here; nothing else changes. IPA is accurate but most young readers
 *   can't decode it — the tap-to-hear audio is the real pronunciation aid.
 */

const PHONETICS: Record<string, string> = {
  // ── Colours ──
  red: '/rɛd/', orange: '/ˈɔrɪndʒ/', yellow: '/ˈjɛloʊ/', green: '/ɡriːn/',
  blue: '/bluː/', purple: '/ˈpɜrpəl/', pink: '/pɪŋk/', brown: '/braʊn/',
  black: '/blæk/', white: '/waɪt/', gray: '/ɡreɪ/', grey: '/ɡreɪ/',
  gold: '/ɡoʊld/', golden: '/ˈɡoʊldən/', silver: '/ˈsɪlvər/', beige: '/beɪʒ/',
  tan: '/tæn/', teal: '/tiːl/', maroon: '/məˈruːn/', navy: '/ˈneɪvi/',
  cyan: '/ˈsaɪæn/', magenta: '/məˈdʒɛntə/', turquoise: '/ˈtɜrkwɔɪz/',
  violet: '/ˈvaɪələt/', indigo: '/ˈɪndɪɡoʊ/', cream: '/kriːm/', ivory: '/ˈaɪvəri/',

  // ── Shapes ──
  round: '/raʊnd/', square: '/skwɛr/', circular: '/ˈsɜrkjələr/', circle: '/ˈsɜrkəl/',
  oval: '/ˈoʊvəl/', triangular: '/traɪˈæŋɡjələr/', triangle: '/ˈtraɪæŋɡəl/',
  rectangular: '/rɛkˈtæŋɡjələr/', rectangle: '/ˈrɛktæŋɡəl/', flat: '/flæt/',
  curved: '/kɜrvd/', straight: '/streɪt/', pointed: '/ˈpɔɪntɪd/',
  spherical: '/ˈsfɛrɪkəl/', sphere: '/sfɪr/', cylindrical: '/sɪˈlɪndrɪkəl/',
  cube: '/kjuːb/', cubic: '/ˈkjuːbɪk/', hexagonal: '/hɛkˈsæɡənəl/',
  star: '/stɑr/', heart: '/hɑrt/', diamond: '/ˈdaɪmənd/',

  // ── Sizes ──
  big: '/bɪɡ/', small: '/smɔl/', large: '/lɑrdʒ/', tiny: '/ˈtaɪni/',
  huge: '/hjuːdʒ/', little: '/ˈlɪtəl/', medium: '/ˈmiːdiəm/', long: '/lɔŋ/',
  short: '/ʃɔrt/', tall: '/tɔl/', wide: '/waɪd/', narrow: '/ˈnæroʊ/',
  thick: '/θɪk/', thin: '/θɪn/', giant: '/ˈdʒaɪənt/', massive: '/ˈmæsɪv/',
  miniature: '/ˈmɪniətʃər/',

  // ── Textures ──
  soft: '/sɔft/', hard: '/hɑrd/', smooth: '/smuːð/', rough: '/rʌf/',
  bumpy: '/ˈbʌmpi/', fuzzy: '/ˈfʌzi/', furry: '/ˈfɜri/', silky: '/ˈsɪlki/',
  sticky: '/ˈstɪki/', slippery: '/ˈslɪpəri/', grainy: '/ˈɡreɪni/', fluffy: '/ˈflʌfi/',
  prickly: '/ˈprɪkli/', coarse: '/kɔrs/', slimy: '/ˈslaɪmi/', squishy: '/ˈskwɪʃi/',
  scratchy: '/ˈskrætʃi/',

  // ── Materials ──
  wooden: '/ˈwʊdən/', wood: '/wʊd/', metal: '/ˈmɛtəl/', metallic: '/məˈtælɪk/',
  plastic: '/ˈplæstɪk/', glass: '/ɡlæs/', fabric: '/ˈfæbrɪk/', paper: '/ˈpeɪpər/',
  rubber: '/ˈrʌbər/', ceramic: '/səˈræmɪk/', stone: '/stoʊn/', leather: '/ˈlɛðər/',
  cotton: '/ˈkɑtən/', wool: '/wʊl/', clay: '/kleɪ/',

  // ── Temperature / weight ──
  hot: '/hɑt/', cold: '/koʊld/', warm: '/wɔrm/', cool: '/kuːl/',
  heavy: '/ˈhɛvi/', light: '/laɪt/', freezing: '/ˈfriːzɪŋ/', lightweight: '/ˈlaɪtweɪt/',

  // ── Optical / light ──
  shiny: '/ˈʃaɪni/', dull: '/dʌl/', matte: '/mæt/', glossy: '/ˈɡlɔsi/',
  transparent: '/trænsˈpɛrənt/', opaque: '/oʊˈpeɪk/', clear: '/klɪr/',
  bright: '/braɪt/', dark: '/dɑrk/', sparkly: '/ˈspɑrkli/', glowing: '/ˈɡloʊɪŋ/',
  reflective: '/rɪˈflɛktɪv/', translucent: '/trænsˈluːsənt/',

  // ── Patterns ──
  striped: '/straɪpt/', spotted: '/ˈspɑtɪd/', dotted: '/ˈdɑtɪd/', plain: '/pleɪn/',
  patterned: '/ˈpætərnd/', checkered: '/ˈtʃɛkərd/', swirled: '/swɜrld/',

  // ── Hard-mode escalations ──
  rigid: '/ˈrɪdʒɪd/', flexible: '/ˈflɛksəbəl/', inflexible: '/ɪnˈflɛksəbəl/',
  dense: '/dɛns/', sturdy: '/ˈstɜrdi/', fragile: '/ˈfrædʒəl/', elastic: '/ɪˈlæstɪk/',
  firm: '/fɜrm/', solid: '/ˈsɑlɪd/', hollow: '/ˈhɑloʊ/', brittle: '/ˈbrɪtəl/',
  compact: '/kəmˈpækt/',
};

/** Return IPA for a property word, or null if we don't have it (UI hides it). */
export function getPhonetic(word: string | null | undefined): string | null {
  if (!word) return null;
  return PHONETICS[word.trim().toLowerCase()] ?? null;
}
