-- ============================================================================
-- 20260604_quests_is_daily_marker.sql
-- Skanlore — mark generated daily quests so they stay OUT of the curated
-- library. Pairs with the ensure-daily-quest avoid-list + fallback changes and
-- the 20260604_daily_quest_rolling_window.sql RPC.
--
-- WHY: ensure-daily-quest inserts generated dailies as visibility='public',
-- is_active=true, so they currently appear in the QuestMap library (and, after
-- the tier flip, as locked clutter). The fork decision is that dailies are
-- always freshly generated and kept out of the curated library; aged-out ones
-- are simply not surfaced. is_daily=true is the marker the client uses to
-- exclude them from loadQuests, and that ensure-daily-quest's fallback uses to
-- reuse a prior generated daily instead of a curated quest.
--
-- NO BACKFILL: existing daily_quests rows mix freshly-generated quests with
-- REUSED curated/seed dungeons (e.g. the 1111…/2222… starters). There is no
-- reliable column today to tell them apart (created_by is null for both), so a
-- blanket "any quest with a daily_quests row → is_daily=true" would wrongly
-- pull curated free dungeons out of the library. Therefore is_daily is set
-- ONLY on dailies generated from this change onward. The handful of already-
-- generated daily rows stay is_daily=false (visible in the library as before);
-- clean those up manually later if desired.
--
-- REVERSIBILITY: DROP COLUMN public.quests.is_daily; (the index drops with it).
-- ============================================================================

-- ─── 1. Marker column ───────────────────────────────────────────────────────
ALTER TABLE public.quests
  ADD COLUMN IF NOT EXISTS is_daily boolean NOT NULL DEFAULT false;

COMMENT ON COLUMN public.quests.is_daily IS
  'True for quests generated by ensure-daily-quest as the global daily quest. '
  'Excluded from the curated QuestMap library (client loadQuests filters '
  'is_daily=false); surfaced only via the daily mechanism + the rolling 3-day '
  'free window. Set on generation from 2026-06-04 onward; existing dailies '
  'were not backfilled (cannot reliably distinguish generated vs reused '
  'curated quests).';

-- ─── 2. Partial index for the fallback "most recent generated daily" lookup ──
CREATE INDEX IF NOT EXISTS quests_is_daily_recent_idx
  ON public.quests (created_at DESC)
  WHERE is_daily = true;

-- ─── Sanity log ─────────────────────────────────────────────────────────────
DO $$
DECLARE
    n integer;
BEGIN
    SELECT count(*) INTO n FROM public.quests WHERE is_daily = true;
    RAISE NOTICE 'quests_is_daily_marker: column added; is_daily=true rows = % (expect 0 pre-generation)', n;
END $$;
